// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { ChatProvider } from "@/components/chat-provider";
import "./globals.css";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "bimmerllm",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="min-h-screen antialiased">
        <ChatProvider>
          <SidebarProvider>
            <div className="flex h-svh w-full">
              {/* 左侧：固定宽度 sidebar */}
              <AppSidebar />

              {/* 右侧：自适应宽度内容区域 */}
              <main className="flex-1 flex flex-col">{children}</main>
            </div>
          </SidebarProvider>
        </ChatProvider>
      </body>
    </html>
  );
}
